import ast
import os
import json  # NEW: For saving the data
from pathlib import Path

def get_file_imports(file_path):
    """Extracts imports from a single file (No changes here)."""
    imports = []
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            tree = ast.parse(f.read())
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.append(alias.name)
            elif isinstance(node, ast.ImportFrom) and node.module:
                imports.append(node.module)
    except Exception:
        return []
    return imports
def build_repo_map(root_directory):
    repo_map = {}
    base_path = Path(root_directory)
    internal_modules = {p.stem for p in base_path.rglob('*.py')}
    
    for root, dirs, files in os.walk(base_path):
        if "agent_engine" in root or ".git" in root:
            continue
            
        for file in files:
            if file.endswith(".py"):
                full_path = Path(root) / file
                
                # --- FIX START ---
                # We must calculate the relative path from demo_repo
                # Example: sub_logic/database.py instead of just database.py
                rel_path = full_path.relative_to(base_path)
                # --- FIX END ---
                
                all_imports = get_file_imports(full_path)
                internal_only = [imp for imp in all_imports if imp in internal_modules]
                
                # Use the relative path string as the key
                repo_map[str(rel_path)] = internal_only
                
    return repo_map

def get_file_skeleton(file_path):
    """Extracts function and class names from a file to create a 'Skeleton' view."""
    skeleton = []
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
            if not content.strip():
                return ["(Empty File)"]
            tree = ast.parse(content)
            
        for node in ast.walk(tree):
            # Look for Class definitions
            if isinstance(node, ast.ClassDef):
                skeleton.append(f"Class: {node.name}")
            # Look for Function definitions
            elif isinstance(node, ast.FunctionDef):
                # Get the arguments/parameters of the function
                args = [arg.arg for arg in node.args.args]
                skeleton.append(f"Function: {node.name}({', '.join(args)})")
    except Exception:
        return ["Error parsing skeleton"]
        
    return skeleton

def generate_context_report(repo_map, root_dir):
    """Combines the map and the skeletons. Fixed for sub-folders."""
    report_path = Path("CONTEXT.md")
    root_path = Path(root_dir) # Ensure root_dir is a Path object
    
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("# 🏗️ Project Architecture & Context Map\n\n")
        f.write("This file is automatically generated by the Architect Agent.\n\n")
        
        for file_rel_path, deps in repo_map.items():
            f.write(f"## 📄 {file_rel_path}\n")
            
            # Use joinpath to get the correct full path for the skeleton scanner
            full_file_path = root_path / file_rel_path
            
            f.write(f"**Relies on:** `{', '.join(deps) if deps else '(No internal dependencies)'}`  \n")
            f.write("### 🦴 Logic Signatures:\n")
            
            skeleton = get_file_skeleton(full_file_path)
            for line in skeleton:
                f.write(f"- {line}\n")
            
            f.write("\n---\n\n")
            
    print(f" Successfully generated {report_path}")
    
def calculate_performance_score(root_dir, report_file):
    """Calculates the 1-10,000 score based on character reduction."""
    original_chars = 0
    # Count every character in your source code
    for root, _, files in os.walk(root_dir):
        for file in files:
            if file.endswith(".py"):
                with open(os.path.join(root, file), "r", encoding="utf-8") as f:
                    original_chars += len(f.read())
    
    # Count characters in your clean skeleton report
    with open(report_file, "r", encoding="utf-8") as f:
        skeletal_chars = len(f.read())
    
    if original_chars == 0: return 0
    
    # The Formula
    reduction_ratio = 1 - (skeletal_chars / original_chars)
    score = int(reduction_ratio * 10000)
    return max(0, min(score, 10000)) # Keep it between 0 and 10,000

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Context Excavator")
    parser.add_argument(
        "--path",
        type=str,
        default="demo_repo",  # if no path given, uses demo_repo as before
        help="Path to the project you want to analyze"
    )
    args = parser.parse_args()

    # args.path is whatever folder the user points at
    # if they type --path ../their-project, ROOT becomes ../their-project
    # if they type nothing, ROOT stays "demo_repo" exactly as before
    ROOT = args.path
    REPORT = "CONTEXT.md"

    # Everything below is exactly what you had before, nothing changes
    my_repo_map = build_repo_map(ROOT)
    generate_context_report(my_repo_map, ROOT)

    final_score = calculate_performance_score(ROOT, REPORT)

    print(f"---  QUEST PERFORMANCE SCORE ---")
    print(f"Score: {final_score} / 10,000")
    print(f"Calculation Method: Context Leverage Factor (CLF)")